### ISSUE TITLE
audio/webm Mime Type with SSL

### ISSUE THREAD

**Issue by dom-robinson** [webcast/webcaster#18]
So i realise these has had an update, and i am reworking my ui to work with the new webcast.js and so on.
I can now handshake and connect using SSL but when i try to start streaming i get an error:

`Unable to decode stream of type "audio/webm"!`

I have tried editing client.js, line 1251

`    audioMimeTypes = enabledMimeTypes([
      {
        name: "Opus audio",
        value: "audio/webm;codecs=opus"
      }
    ]);
    `

But any Mime type other than exactly as is returns `Unable to decode stream of type " "!`

`
#opam version 2.0.4
opam switch set 4.04.1
eval $(opam env)

#liquisoap version 1.4.4
liquidsoap file.liq
`

file.liq>>
`
set("harbor.bind_addr","0.0.0.0")
set("harbor.ssl.certificate","fullchain.pem")
set("harbor.ssl.private_key", "privkey.pem")

live = input.harbor.ssl("test-harbor",port=8020,password="hackme")

emergency = single("/home/ubuntu/fallback.mp3")
radio = fallback(track_sensitive=false,[live,emergency])

output.icecast(%vorbis, host = "decks.XXX.com", port = 8080, password = "XXXXX", mount = "YYY")
`

I can connect mp3 encoders such as BUTT to the harbor using TLS. But the webcaster is returning this 'webm' error after handshaking.

Is there something i need to do to to add webm support to liquidsoap? Or is it an issue due to the input.harbor.ssl? I am a bit lost where to go.

**Comment by dom-robinson** [comment]
@toots  -  im increasingly of the opinion that i need to add webm support to my liquidsoap. if that makes sense is there a dark art to enabling it (or a particular version to use with the new webcast.js) I am wondering about performing a quick test with video to see if its the 'audio only' side that may have slipped through dev-testing? 

Hope all well with you..

Dom

**Comment by toots** [comment]
Do you have the `ffmpeg` decoder enabled?

**Comment by dom-robinson** [comment]
I beleive so. 

```
$ which ffmpeg
/usr/bin/ffmpeg
```

```
ffmpeg version 4.2.4-1sergeyd8.2~18.04.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version='1sergeyd8.2~18.04.1' --libdir=/usr/lib/x86_64-linux-gnu --shlibdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --enable-version3 --enable-nonfree --disable-libtesseract --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-libaom --disable-decoder=libaom_av1 --enable-libass --enable-libbluray --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libfdk-aac --enable-libfontconfig --enable-libfreetype --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-frei0r --enable-libx264 --enable-libmfx --enable-ffnvcodec --enable-nvenc --enable-nvdec --enable-libsvthevc --enable-libsvtav1 --enable-libsvtvp9 --enable-shared
```
  
 And 
 
 ```
ffmpeg -decoders | grep vpx
```
 
 shows
 
 
 ```
...
 V....D libvpx               libvpx VP8 (codec vp8)
 V....D libvpx-vp9           libvpx VP9 (codec vp9)
 ... 
```

**Comment by dom-robinson** [comment]
Ah - seem to have a connection happening now. I added this to the .liq. However still not passing audio, but thats a new issue.

Ill close as soon as i get audio through.

```
set("decoder.external.ffmpeg.path","ffmpeg")
set("decoder.file_extensions.ffmpeg",["mp1","mp2","mp3","m4a","m4b","m4p","m4v","m4r","mov","3gp","mp4","wav","flac","ogv","oga","ogx","ogg","opus","wma","webm","$
set("decoder.mime_types.ffmpeg",["audio/vnd.wave","audio/wav","audio/wave","audio/x-wav","audio/aac","audio/aacp","audio/x-hx-aac-adts","audio/flac","audio/x-flac$

```

**Comment by dom-robinson** [comment]
Working now - thanks for the pointer @toots :)
