### ISSUE TITLE
Unexpected response code: 404

### ISSUE THREAD

**Issue by EitanGoldfrad** [webcast/webcaster#2]
Hey,

I'm Trying to stream from webcaster to icecast using liquidsoap.

I get the error in the console "WebSocket connection to 'ws://<server-ip>:9052/mount' failed: Error during WebSocket handshake: Unexpected response code: 404"

Any idea what's wrong?

P.s the port 9052 is open.

**Comment by toots** [comment]
Hi @EitanGoldfrad 

Icecast does not implement the websocket streaming protocol, you will need to use liquidsoap as receiver and then pass the stream over to icecast.
