### ISSUE TITLE
Catch failure to allow access to mic

### ISSUE THREAD

**Issue by NTShop** [webcast/webcaster#4]
Can you please add a bit of code that catches the condition where a user is asked to allow mic access but denies it? 

Specifically the function Node.prototype.createMicrophoneSource calls navigator.mediaDevices.getUserMedia, the user  may not allow mic access. I can't figure out how to catch that condition, so I'm wonder if you can add such code, or maybe tell me how to do it? 

Normally that wouldn't be difficult, but due to the way you've written that bit of code (beyond my knowledge level) it's not clear to me how to implement catching that error.

**Comment by NTShop** [comment]
After more research apparently this is a moot point because for some strange reason Firefox returns nothing on a call to getUserMedia unless the user approves or denies mic access. So if the user simply dismisses the dialog prompt (closes by clicking the X) then the request remains pending and Firefox returns nothing. Wow. I'll handle that condition another way.

**Comment by toots** [comment]
Ok, thanks for investigating. Closing!
